/**
 * @type import('hardhat/config').HardhatUserConfig
 */

//  dotenv package: lets us use environment variables within our Node.js application
//  require("@nomiclabs/hardhat-ethers"): runs the user-friendly methods provided by Ether in our deploy scripts
//  defaultNetwork: specifies which network Hardhat should use when deploying our application (Ropsten Testnet)
//  accounts : a private key generated by MetaMask that allows our application to connect to
//  our MetaMask virtual wallet to complete a transaction
//  url: specifies the URL that our Node.js application is hosted on (Alchemy servers)

require("dotenv").config();
require("@nomiclabs/hardhat-ethers");
const { API_URL, METAMASK_PRIVATE_KEY } = process.env;
module.exports = {
  solidity: "0.8.0",
  defaultNetwork: "goerli",
  networks: {
    hardhat: {},
    goerli: {
      url: API_URL,
      accounts: [`0x${METAMASK_PRIVATE_KEY}`],
    },
  },
};
